---
lightbox: true
---

# Outline {.unnumbered}

**BEDA is taught under three modules, each led by a different academic, from lectures to practicals.** Because of this, you will notice that the delivery differs between modules, and some content may be *repeated*. This is intentional. We believe that repetition is key to learning some of the most important concepts in study design and statistics. Some techniques *need* to be applied in different situations to be fully understood. 

## Structure

**Module 1**: led by Januar Harianto, covers the fundamentals. We expect most of you to be familiar with the basic statistical techniques, but we will go through the standard concepts and unify them under a linear modelling framework. In addition we introduce to you the concept of study design and how it influences the results of your analysis. 

**Module 2**: led by Clare McArthur, critically assesses study designs that have already been done. Using real data examples, we will look at how variations in study design can influence the results. You *will* notice that the concepts from Module 1 are applicable to more *complex* models. You will also start working on Report 1 which requires you to design and analyse an experiment.

**Module 3**: led by Mathew Crowther, focuses on the application of statistical techniques to real-world data that is often complex and messy -- and how to deal with it using multivariate techniques. You will start working on Report 2 which requires you to collect and analyse data from your environment, rather than a controlled experiment.

## Lectures, Labs & drop-in sessions

**Lectures** are *compulsory* and are held on Tuesdays and Wednesdays at different locations:

- Tuesdays: 10am-11am -- [The Quad General Lecture Theatre](https://venueweb.sydney.edu.au/A14.02.K2.05)
- Wednesdays: 10am-11am -- [Carslaw Lecture Theatre 159-259](https://venueweb.sydney.edu.au/F07.02.159-259)

**Labs** are held on Tuesdays, Wednesdays and Fridays. You will be assigned to a lab and you *must* attend the lab session you are assigned to -- attendance is recorded. Labs are also *compulsory* at either 2pm-4pm or 4pm-6pm. Check your timetable for your assigned lab time.

All labs are held in [Carslaw Lab 307](https://venueweb.sydney.edu.au/F07.03.307).

**Drop-in sessions** are held weekly on Zoom. These are optional sessions where you can ask questions about the content covered in the lectures and labs and get help with your assessments. The schedule for these sessions will be posted on Ed, as the times may vary depending on the time of the semester.

## Assessements

The assessments for this unit are outlined in @tbl-assessments.
Compulsory assessments are marked in **bold** and must be attempted and submitted prevent a fail grade.


Assessment | Type | Mode | Due | Weight
:--- | :--- | :--- | :--- | :--- | :---
Quiz 1 | Ind | Online | Week 1 | 0%
Quiz 2 | Ind | Online | Week 2 | 0%
Quiz 3 | Ind | Online | Week 3 | 0%
**Evaluation Quiz** | **Ind** | **Online** | **Week 4** | 15%
**Report 1** | **Ind** | **Submitted work** | **Week 9** | 25%
Report 2 -- data upload | Grp | Submitted work | Week 11 | 5%
**Report 2** | **Ind** | **Submitted work** | **Week 13** | 15%
**Final Exam** | **Ind** | **In-person** | **Exam period** | 40%

: Assessments for BIOL2022. For detailed information, see Canvas. {#tbl-assessments}

### Late penalties
- Failure to complete the Quiz on time will result in a 0 mark.
- A penalty of 5% per day will be applied for late submissions of all assessments, except where otherwise stated (e.g. an extension has been granted).

## Generative AI

There's no escaping generative AI (GenAI) -- so let's use it responsibly. The University maintains a Canvas site [AI in Education](https://canvas.sydney.edu.au/courses/51655) which provides information on the use of AI tools in your studies. Some useful links include:

- [Different generative AI options](https://canvas.sydney.edu.au/courses/51655/pages/different-generative-ai-tools)
- [Acknowledging and referencing](https://canvas.sydney.edu.au/courses/51655/pages/acknowledging-and-referencing-the-use-of-ai?wrap=1) the use of AI
- the [Guidelines](https://canvas.sydney.edu.au/courses/51655/pages/university-of-sydney-guidelines?wrap=1) for the use of AI in your studies

In most cases, we're happy for you to use it **as long as you're transparent about using it** and adhere to the academic integrity guidelines while doing so. Remember that you are here to learn -- GenAI is in fact an excellent tool to help you understand the concepts better, but using it to do your work defeats that  purpose. 

Your report guidelines will outline our expectations on the use of *any* AI tool. If you're unsure, ask us!


