book:
  title: Biology Experimental Design and Analysis
  subtitle: BIOL2022 Unit Manual
  author: 
    - Dr. Januar Harianto
    - Prof. Clare McArthur
    - Prof. Matthew Crowther
  date: today
  site-url: https://biol2022.github.io/BIOL2022-unit-manual/
  sidebar:
    # background: "#EEE5E9"
    logo: assets/bedalogo.svg
    search: true
    style: floating
  chapters: 
    - index.qmd
    - 01-outline.qmd
    - 02-policies.qmd
    - 03-study.qmd
    - "---"
    - part: "**Module 1**"
      chapters:
      - module01/101-intro.qmd
      - module01/102-week01.qmd
      - module01/103-week02.qmd
      - module01/105-images.qmd
      - module01/106-species-id.qmd
      - module01/104-week03.qmd
    - part: "**Workshops**"
      chapters:
      - module01/w01-intro.qmd
      - module01/w02-tidy-data.qmd
      - module01/w03-model-fitting-assumptions.qmd
    - "---"
    - part: "**Module 2**"
      chapters:
        - module02/201-intro.qmd
        - module02/202-timeline.qmd
        - module02/203-projects.qmd
        - module02/204-report1.qmd
    - "---"
    - part: "**Module 3**"
      chapters:
      - module03/301-intro.qmd
      - module03/302-week09.qmd
      - module03/303-week10.qmd
      - module03/304-week11.qmd
      - module03/305-week12.qmd
    - "---"
    - 04-cheatsheets.qmd
    - 05-feedback.qmd
bibliography: references.bib

format:
  html:
    number-sections: true
    number-depth: 1
    toc: true
    toc-expand: true
    toc-depth: 3
    code-link: true
    # theme: cosmo # cosmo zephyr
    html-math-method: katex
    published-title: "Last updated"
    grid:
      sidebar-width: 300px