---
author: Mathew Crowther
---
# **Module 3 (Weeks 9 -- 13)** {.unnumbered}

## Preamble
The aim of this component of the practical series is to introduce you to several common techniques for analysing multivariate data. At the end of them you will:

- Be familiar with the principles underpinning principal components analysis (PCA), and non-metric multidimensional scaling.
- Be familiar with the principles underpinning multivariate hypothesis testing using permutational techniques such as ANOSIM and PERMANOVA.
- Planning and conducting experiments to test multivariate hypotheses.
- Know how to perform these analyses using relevant software.
- Be able to interpret, present and report on these analyses. 

## Background 

Multivariate analyses are becoming more prevalent in biology as tools performing the necessary complex computations become more accessible. As the lectures outline, this accessibility has given rise to the uncritical use of methods leading to inappropriate analyses being used to deal with multivariate data sets. At the very least, biologists need to have a working understanding of how to choose appropriate tests and how to identify when someone has chosen poorly.

Some of the more common uses of multivariate approaches permit us to describe complex patterns simply, identify patterns of groupings in complex data sets and test statistical hypotheses using multivariate datasets. 

In this section of the unit, you will be able to practice performing these multivariate techniques using sample data sets. Then you need to demonstrate your ability to use these multivariate methods to analyse data that you will collect in groups to highlight the nuances of different techniques. Whilst best practice normally dictates that we would normally decide on appropriate tests before we collect our data, this task will enable us to explore options for analysis more effectively. 

## Analyses and programs we’ll use
The main programs we will use are **SPSS** and **PRIMER**. However, R instructions for all methods, in the form of R scripts, will be supplied on Canvas for those who prefer to use R.

- **PCA** -- Principal components analysis lets us extract a reduced dataset from a larger dataset, accounting for as much variance as possible in the original more complex dataset. This will be useful for your habitat data as we can determine a reduced number of newly derived variables to describe them. We will do this in SPSS (or R). 
- **nMDS and multivariate hypothesis testing (using ANOSIM, PERMANOVA and SIMPER)** -- Mainly used to produce an ordination in order to visualize patterns in the multivariate cloud of data (by reducing dimensions in some way) and also to rigorously test explicit hypotheses concerning those patterns by reference to a priori groups or relationships with predictors, such as environmental variables. We will use PRIMER for this (or R).
- **ANOSIM** -- testing hypotheses comparing different groups based on their similarity (Among c.f. within) using distance measures. Most effective with simple designs. We will use PRIMER for this (or R).
- **PERMANOVA** -- more powerful approach to multivariate hypothesis testing using permutational methods, capable of analysing more complex designs. We will use PRIMER for this (or R).
- **SIMPER** --  used when a significant difference is found to identify which components of the data set are driving the differences (e.g. the contribution each species makes to differences among communities. We will use PRIMER for this (or R).

## Timeline

- **Week 9**: introduction, PCA of lecture data and designing model systems to test multivariate hypotheses (in groups) for your reports. 
- **Week 10**: group presentations of model systems and experimental design, and how to perform nMDS, PERMANOVA (and ANOSIM) and SIMPER using sample data.
- **Week 11**: submitting your complete datafiles onto Canvas, analysing your report data.
- **Week 12**: additional analyses and summary of findings and guidelines for describing multivariate methods and results for your report.
- **Week 13**: final report due.
