---
title: Week 11
---

:::{.callout-tip appearance="simple"}
## Objectives 
The aim of this component of the practical series is to introduce you to several common techniques for analysing multivariate data. At the end of them you will:

- Be familiar with the principles underpinning principal components analysis (PCA) and non-metric multidimensional scaling.
- Be familiar with the principles underpinning multivariate hypothesis testing using permutational techniques
- Planning and conducting experiments to test multivariate hypotheses
- Know how to perform these analyses using relevant software
- Be able to interpret, present and report on these analyses. 
For this specific practical you will:
- Analyse and interpret your group data using multivariate techniques learnt in weeks 1 (PCA) and 2 (nMDS, PERMANOVA, SIMPER (if appropriate, etc). 
- Perform analyses (ANOVA, regressions etc) to test additional univariate hypotheses.
:::

## Outline

At the end of the practical you should have:

1. Appropriate outputs for your community structure analyses:
   - Cluster analysis details and dendrogram (if appropriate)
   - nMDS (saved as suitable image file)
   - PERMANOVA results (in rtf/doc file)
   - SIMPER if justified
2. Appropriate outputs for your PCA:
   - RTF file with SPSS or R output
3. Univariate tests using your PCA results
   - RTF file with SPSS or R output with Regression and/or ANOVA results (testing hypotheses using your newly derived PCs)

## Your own data
At this stage it’s very easy to fiddle with your data – is there any reason you might want to standardise or transform your data in any way? Some things to consider at this stage:

- Do the abundances matter?
- Are you intending to make every sample equal?
- Would it be worth analysing using your data at a higher “taxonomic” level?


## Tips for PRIMER
The graphics are not fantastic – for some outputs you may need to save the coordinates and make a new graph. You can save the images as a windows metafile or bitmap if you wish, they are good enough for your report. Resolution is too low for most journals. You should save appropriate output files using standard formats you can incorporate into your report. 

If you don’t complete your analyses, I will make the program available to you outside of prac times. There will also be time in Week 12 to do any extras.

