---
author: Januar Harianto
---

# Module 1 (Weeks 1 -- 3) {.unnumbered}

## Preamble

**Science is a process of asking the right questions in the right way, such that we can draw meaningful conclusions when we collect data to answer them.** 
This is not as easy as it sounds, but it remains a fundamental skill in scientific enquiry. We want to be able to ask questions in a quantitative manner to draw distinctions between different explanations for the phenomena we observe.

*Before* we can start performing t-tests, regressions and ANOVAs; before we can start implementing *fancy* machine learning algorithms; before we can start using the *latest* and *greatest* tools for data analysis, **we need to be able to ask the right questions**. 

So let's (re)-start with the fundamentals.

## What this module is about

**Module 1** is designed to help you develop the fundamental skills in scientific enquiry. Together, we will cover experimental design, model formulation and sampling design. Each week, we start off with a short **30-minute workshop** to introduce you to the concepts and techniques. You will then work through the practical.


## Outline
[**Week 1 Introduction**](102-week01.qmd) -- We will introduce you to the practical structure, the software you will be using throughout the unit and also get you started on some modelling exercises.

[**Week 2 Data sampling**](103-week02.qmd) -- Explore the concept of sampling and how to design a study that can draw meaningful conclusions – by collecting data from images. More modelling exercises will be provided.

[**Week 3 Data analysis**](104-week03.qmd) -- Practice data analysis and diagnostics using the data you have collected in the previous week, and discuss what worked and what didn't. 

