---
title: Week 1 -- Introduction
---

## Welcome
Welcome to the first practical of BEDA. We will use this time to introduce you to the software you will be using throughout the unit and also get you started on some modelling exercises.

**The only expectation for this practical is that you have attended the first lecture.** If you were not able to attend, please watch the recording before you come into the laboratory!

In Module 1, all practicals begin with a **workshop**. The workshop is a short class that goes through the key concepts of the week and may also include some resources for you to use in the practical. The workshop is followed by **exercises** that you will complete in the laboratory. The exercises are designed to help you understand the concepts covered in the lectures and gives you a chance to practice study design and data analysis.

Workshop slides are available on Canvas through the Weekly Lecture page.

### Workshop
In today's workshop we will go through:

- Getting to know one another
- Introduction to R, SPSS, Jamovi and JASP

The workshop should take no more than 30 minutes (**unless Januar talks too much**). After the workshop, you will be given time to complete the exercises. 


## Exercise 1 -- cheatsheets

### Background
If you are new to statistical software like R or SPSS, or often forget the commands you need to use, you are not alone. In this short exercise we will introduce you to **cheatsheets**, which are quick reference guides that help you remember important functions and commands. In this exercise you will pick from a list of cheatsheets and try to complete the analytical tasks provided. You can work in groups to discuss the cheatsheets, but try to complete them on your own.

### Try out a cheatsheet
1. In the **Cheatsheets** section, you will find a list of cheatsheets that have already been created for you. These cheatsheets are NOT complete and we will improve them as we go along. 
2. **Choose a cheatsheet** that you would like to try out -- it could be something that you are *not* familiar with, or you could also choose one that you have some experience with to see if it aids your understanding.
3. **Try to complete the tasks** by following the steps on the cheatsheet. If you get stuck, don't worry! You can ask your peers or the demonstrators for help, and you may provide feedback so that it can be improved.

### Provide feedback 
Once you are done, please provide feedback on the cheatsheets you have tried out. You can do this by submitting a comment on the form provided to you on the cheatsheets page. The form will ask you to rate the cheatsheet, and should take no more than a minute to complete, so please help us out!

Your feedback will help us improve the cheatsheets for future students.


### Contribute to the cheatsheets (optional)
If you would like to take one step further and *contribute* to the cheatsheets, we are more than happy to accept your suggestions. You can do this in several ways:

- **Submit a pull request on GitHub.** You can find the link to the GitHub repository on the cheatsheet.
- **Submit a comment on Ed.** We will be monitoring the comments and will update the cheatsheets accordingly.
- **Email Januar with your suggestions.** This is absolutely fine!

If your changes are accepted, you will be credited and given co-authorship of the cheatsheet. Your work will be part of the unit's resources and will remain available as a teaching resource. You can also refer to your contribution in your CV or portfolio! For more information, please check with Januar.

::: callout-tip
Suggestions and contributions can be provided throughout the semester, so don't worry if you don't have time to contribute now. We will be updating the cheatsheets regularly.
:::


## Exercise 2 -- introduction to models



### Background

One important aspect of study design is the ability to model data. One way to do it is by using graphical plots, which essentially capture the essence of a study design in a visual form. In this exercise, we will introduce you to the concept of modeling data and get you thinking about how to use models to assist in experimental design and analysis.


#### What is a model?

A model is a simplified representation of a complex system. In the context of data analysis, a model is a way to represent a dataset that allows us to shape testable hypotheses or make predictions about the data. Models can be simple or complex, depending on the data and the research question.

Eventually, you will be presenting what we call an **empirical model**, which looks like a mathematical equation, but actually does not really require *any* mathematical knowledge to understand.


An example of an empirical model is this:

$$y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon$$

Which roughly translates to "the value of $y$ is equal to the sum of the coefficients $\beta_0$, $\beta_1$, and $\beta_2$ multiplied by the values of $x_1$ and $x_2$, plus some error $\epsilon$".

The above may look intimidating, but we can simplify it by thinking of it as a simple relationship, rather than an equation, therefore forming:

$$y \sim x_1 + x_2$$

And so if $y$ is weight, #x_1$ is age and $x_2$ is height, then it is interpreted as

$$\text{weight} \sim \text{age} + \text{height}$$

which translates to "the weight of an object is related to its age and height".

#### Plots as models

For now, we will focus on **graphical models**. These are *plots*, but essentially they are models since they can represent a relationship between two or more variables. 

::: callout-tip
If you can **plot** it, you are already **modelling** it!
:::

### What you will do

This exercise is designed to get you thinking about how to model data while you are designing a study or experiment. Because we are not collecting data in this practical, we will instead look at some example datasets and think about how we would model the variables in them. The datasets are available on Canvas.

::: {.callout-note appearance="minimal"}
## Example
1. Browse the **possum data** in MS Excel. Consider a model of how the **weight** of a possum changes with **age**.
2. Identify the variables: what type of variables are they? Are they continuous, categorical or something else?
3. If you were to design a study to model the relationship between weight and age, what type of plot will help you interpret the data? Are there different plots that you can use depending on the type of data? For example, what if age is a:
   - continuous variable?
   - categorical variable?
4. With the above in mind, draw the plot(s) that you think will help you interpret the data.
:::

Notice that in the example above, you have not performed any data analysis. You are simply considering how to interpret the data, which is an important step in study design. This helps you determine the type of data you need to collect and how to analyse it.

::: callout-important
If you look at the data closely, **there is only one juvenile possum in the dataset**, but this is *not* a problem for this exercise. Your task is to think about how you would model the data in a new study design, not to analyse data that is *already collected*.
:::

If this does not make sense, consult your demonstrators for help. It's early days yet, so don't worry if you don't get it straight away!

### Tasks

**Step 1.** Download and explore the data: penguins.csv and possum.xlsx.

**Step 2.** Identify variables from the data to create the following visualisations:

- Histogram
- Scatterplot
- Boxplot
- Two side-by-side boxplots
- Multiple side-by-side barplots (with or without error bars)

Write down your answers and thought in a document (e.g. Google Docs or MS Word)

**Step 3.** These plots are often associated with specific empirical models, which we will cover in the upcoming weeks. Can you predict what sort of statistical model you would use to analyse the data? Discuss this with your peers and demonstrators.

::: callout-tip
- You are not expected to complete all the plots in one go. You can work on them after the practical.
- If you are new to plotting, **we expect you ask your peers and/or to look up resources online to help you with the plots**. Questions like: "What sort of model does a scatterplot often represent?" or "What is the difference between a histogram and a barplot?" are good starting points.
:::



## End of practical

That's it for today! If you have any questions, please ask your demonstrators. They are here to help you. Remember to submit your feedback on the cheatsheets and to work on the exercises in your own time. We will see you next week for more study design and data analysis!