---
title: Week 3 -- Data analysis
---
## Welcome

In today's practical, we will focus on data analysis. You will work with your group to analyse the data you collected in the previous lab. Cheatsheets are available for you to use, and your demonstrators are ready to help. 

*You may need to clean your data before you can analyse it, so be prepared to spend some time on this.*

## Learning objectives

By the end of this practical, you should be able to:

1. Understand the importance of reproducible analyses.
2. Fit a model to your data.
3. Check if the data meets the assumptions of the model.
4. Interpret the model output.

### What to submit at the end of the practical

**Your plot and model output**, on Google Docs (or equivalent). We will spend some time discussing the results at the end of the tutorial.
   

## Workshop

In today's workshop we will go through **Reproducible analyses and why R is good at it**. We will also demonstrate some AI workflows that are implemented in RStudio. Workshop slides are available on Canvas.

## Lab activity

When ready, work with your group to analyse the data you collected in the previous lab. You will need to:

- Fit your intended model to the data.
- Check if the data meets the assumptions of the model.
- Interpret the model output.

Of particular importance is the assessment of assumptions using residual plots, rather than formal tests of assumptions. 

**Your demonstrators are ready to help.** We expect you to be able to select the appropriate model to your data, but you can consult our cheatsheets and your demonstrators for help.


## Exercise 1 -- Preparing your data for analysis

Your data is available to download on Canvas. Please check that you have all the data you need before proceeding. You also have access to the data collected by other groups should you wish to practice your data analysis skills.

### Background

If you have followed study design principles, the data you have collected should be clean and ready for analysis. However, it is still a good idea to inspect your data further before proceeding with the analysis. This includes a check for:

- Missing data
- Outliers
- Data entry errors
- Assumptions of the statistical model, and whether the data meets them


### Missing data, outliers and data entry errors

These are what we sometimes call systematic errors. They can be detected by looking at the data and checking for unusual values, or cross-checking methods within your group. Make sure to remove or correct these errors before proceeding with the analysis.

## Exercise 2 -- Data analysis

### Fitting a model to data

Recall that you have an empirical model e.g. `y ~ x`. You will need to use an appropriate statistical model to fit this relationship to your data.

:::{.callout-note}
You should already know what model you are fitting to your data as it it part of your study design!
:::


### Checking assumptions

Assumptions need to be checked as they basically tell you whether the model you have fitted is appropriate for your data. If the assumptions are not met, you may need to transform your data or use a different model.

Common assumptions include:

- Normality (of residuals)
- Homogeneity of variance
- Independence of observations

**We recommend looking at residual plots**, rather than formal tests of assumptions. Formal tests of assumptions can be overly sensitive to large sample sizes and can lead to you rejecting a model that is actually appropriate for your data.

**What to do if assumptions are not met?** This is a common problem in data analysis, and interestingly, it is not always a problem. Provided that you have ensured that your data is representative of the population you are interested in, violations of normality can actually be ignored in many cases, **although you should still report them**. A larger problem is homogeneity of variance.


Nevertheless, you get to decide on what to do here to avoid violation of assumptions. The first step would be to try and transform your data. If this does not work, you will need to use a different model or a non-parametric equivalent of the model you are using.

### Statistical testing

Running the statistical test is probably the *least* eventful part of the analytical workflow and will take you a few seconds regardless of the software you are using. Make sure that you record the software used and the specific statistical technique selected such that the analysis is **reproducible**.


### Interpretation

Interpreting the output of a statistical test is a skill that takes time to develop. You will need to be able to:

- Understand the important parts of the output e.g. F-statistic, p-value, degrees of freedom, etc.
- Explain what the output means in the context of your data.
- Explain what the output means in the context of your research question.

Your lectures and this week's workshop will help you develop these skills.

## Submit your results

Once complete, please upload your results to Google Docs (or equivalent) and share the link with your demonstrator. We will discuss the results together.

## End

That's it. Three weeks in and Module 1 is almost over We hope that the content has been useful and that you are starting to see how study design and data analysis are interlinked. In Module 2, you will need to use the skills you have developed to design and analyse an experiment for Report 1.