---
title: Report 1 -- **Projects**
---

::: callout-important
**FOR ALL PROJECTS – KEEP YOUR EXPERIMENT SIMPLE.**

 - You should be able to design an experiment that could be analysed using one of the following: 
   - a paired t-test, 
   - an independent t-test, 
   - 1-way ANOVA, 
   - 2-way ANOVA, 
   - correlation, 
   - linear regression, 
   - Chi-Square analysis or 
   - logistic regression. 
- General linear models (GLMs, which cover a lot of the analyses above anyway) and generalised linear mixed models (GLMM) are *fine* **PROVIDED you do them correctly**. 
- You will be rewarded for doing a simple appropriate analysis correctly. 
- **You will be penalised for doing a complicated analysis wrong.**

:::

-----

#### Project 1 – Plant-herbivore interactions: Does previous damage to tomato plants affect their vulnerability to subsequent herbivory? Does the amount of previous damage matter?

**Background**: Many plants have plant secondary metabolites (PSMs), which often play a role in defence against herbivores. In some plant species, PSMs can be induced (levels increase) after damage from herbivores chewing on leaves. This change can take place within a day, affecting subsequent leaf damage by herbivores, and result in less subsequent damage. Is the evidence consistent with this idea in tomatoes?

**Variation**: If you want to answer a more complicated question, you could ask whether the amount of initial damage (a little versus lots?) affects the outcome.

::: callout-note
You do not need to measure PSMs. Rather, they provide a potential mechanism to explain any difference in subsequent herbivory.
:::

-----

#### Project 2 – Plant-herbivore interactions: Does previous damage affect vulnerability of vegetables to subsequent herbivory? Does it depend on plant species?

**Background**: Many plants have plant secondary metabolites (PSMs), which often play a role in defence against herbivores. In some plant species, PSMs can be induced (levels increase) after damage from herbivores chewing on leaves. This change can take place within a day, affecting subsequent leaf damage by herbivores, and result in less subsequent damage. Is the evidence consistent with this idea? Does it depend on plant species? 

::: callout-note
You do not need to measure PSMs. Rather, they provide a potential mechanism to explain any difference in subsequent herbivory.
:::

-----

#### Project 3 & 9 – Foraging strategies in relation to food type: Do ants prefer some food over others?

**Background**: Ants spend a lot of their time searching for food, but the food they find varies in its nutritional and energetic value. Do they just forage for any foods or do they show preferences? Honey and tuna, for example, are very different foods. Do ants care? Honey is a high-carbohydrate low-protein food, while tuna is high protein, low carbs; although there are lots of other differences between these food as well. 

Scout ants go out and look for food, then return to the nest and recruit others to help them. We can understand something about the requirements ants have for different foods by looking at how quickly and/or how many ants are recruited to a food source once it has been located by the scout ant. 

-----

#### Project 4 & 10 – Foraging strategies in relation to costs and benefits: Do ants seek food that is easier to access?  

**Background**: Ants spend a lot of time searching for food, but the effort needed to harvest a given food could affect how they value it. For example, food that is difficult or slow to access (e.g. surrounded by complicated 3-D local habitat or with narrow access points slowing ant traffic) may be less preferred than food that is easy to access.

**Variation**: IF you want to answer a more complicated question, you could ask whether ants balance the effort of getting food against the value of that food. Does food that is hard to access need to be higher in value (e.g. more concentrated) than food that is easy and less energetically costly to access?

Scout ants go out and look for food, then return to the nest and recruit others to help them. We can understand something about the requirements ants have for different foods by looking at how quickly and/or how many ants are recruited to a food source once it has been located by the scout ant. 

-----

#### Project 5 – Germination of native grass seeds in relation to water availability

**Background**: Germination of native plants is triggered by a range of factors in Australia. Some plants need heat initially, others simply need water. Microlaena stipoides (weeping grass) is a native grass that is also used for turf and feed for livestock. It occurs along much of eastern mainland Australia, Tasmania and even in SW Western Australia. It is eaten by our marsupial herbivores, e.g. wombats. Its seeds germinate in a range of conditions within 1 to 2 weeks (>10 &deg;C, faster when warmer), do not need fire but do need moisture. How often it rains may affect whether seeds germinate, in turn affecting recruitment and regeneration. Understanding the relationship between rain (watering) frequency and probability of seeds germinating helps us understand how climate influences the dynamics of our grasslands and use of native plants in agriculture. 

::: callout-note
In your main trial, if you get no germination after 10 days, your group can choose to switch to wheat (Project 6) to ask the same question, because wheat germinates quickly. 
:::

-----

#### Project 6 – Germination and growth of wheat in relation to water availability 

**Background**: Growing crops such as wheat is crucial for food security. In Australia, our rainfall is highly variable, and this can be daunting for farmers wondering whether to sow seed and whether it will germinate if they do. White wheat varieties in Australia can germinate under a range of temperatures (12 to 25 &deg;C), but whether the initial rainfall is light (e.g. shower) versus heavy (e.g. soaking) may affect whether seeds germinate and/or seedlings grow and/or survive. Understanding these relationships is one step in understanding the conditions required to help ensure our food security. 

-----

#### Project 7 & 11 – Are birds active at different times of day? 

**Background**: Birds may be active at different times of day for a variety of reasons. As a first step in understanding bird abundance and diversity we need to be able to measure it and know whether when we measure it makes a difference. If you stand in the same spot and count birds, does the outcome depend on when you did it? Are there other factors you need to control or at least take into account? 

::: callout-note
Animal Ethics conditions apply (see below).
:::

-----

#### Project 8 – Use of urban water bodies by birds: Do characteristics of urban water bodies influence which birds use them?

- **Background**: Bird diversity within cities is affected by many factors, including availability of food, sites for nesting and shelter from predators. Water bodies, such as ponds and lakes, in parks and gardens can attract native (and introduced) birds. The Sydney Council, for example, has upgraded and revegetated the ponds in Sydney Park, just south of Sydney Uni, to encourage water birds. To maximise bird diversity, as well as simply maximise bird numbers, it is important to understand the relationship between characteristics of different water bodies and the diversity of birds they support. 

::: callout-note
Animal Ethics conditions apply (see below).
:::

-----

## Animal Ethics requirements for Projects on birds

If you sign up to these projects, you must follow the animal ethics requirements as approved by the University of Sydney Animal Ethics Committee: 
Project “Ecology teaching – bird surveys”. Project Number: 2022/2148.

You may collect data for up to 10 visits per site over a 2 to 4 week period. 
For the bird survey, you may observe birds, count them and identify each to species if you can, using binoculars where needed. You may observe birds at a site for up to ~ one hour per visit, but must not interfere with nor handle the birds. 

At a given site, the surveyor (1 to 5 students per site) will find a suitable location to observe birds. They will stand or sit still for 15 to 30 minutes per location and count the birds they can see in their site. They may need to move to up to five other locations per site if they have difficulty identifying the birds from afar. The number of each species will be recorded with reference to bird guides, and a total of about one hour will be spent at each site per observation period.

Depending on your project, you may quantify other data, such as vegetation assessments and size of any habitat types including water bodies, at each site, enabling a test of the factors affecting bird abundance and species diversity. 

Observers will remain far enough from birds that the birds are not visibly affected by them (i.e. do not alter their behaviour, either by moving away or by altering what they are doing). This avoids any potential impact of the observer on time or energy budgets of the birds (as described in Bateman et al. 2011). 

Reference: Bateman, P. W., and P. A. Fleming. 2011. Who are you looking at? Hadeda ibises use direction of gaze, head orientation and approach speed in their risk assessment of a potential predator. Journal of Zoology 285:316-323.

### Conditions of bird project approval:

1. You must use the approved monitoring sheet “Bird survey monitoring sheet.xls” which will be provided to you. You may add additional columns or have additional sheets, as you decide, appropriate to your study. 
2. You must take photos of the fieldwork sites and the observers watching the birds (i.e. to see the relative locations of the observers to the birds). 
3. By the end of Week 9, you must post on Canvas: 
   a. A complete legible copy of the final monitoring sheets from (1)
   b. A summary of the total number of (i) native birds, (ii) invasive birds hence (iii) all birds you counted at each site and across all sites over the course of your project, and a list of the sites you monitored, with GPS coordinates.
   c. Clearly and informatively labelled photos from (2).
4. Injured birds: In the very unlikely event that birds are found injured on site: you must:
   a. seek advice from Clare McArthur (clare.mcarthur@sydney.edu.au, subject heading: “BIOL2022 URGENT - bird project”) or other academic in the unit of study, 
   b. while ensuring your own safety first, if necessary arrange to appropriately transport seriously injured animals to the nearest veterinarian for treatment, AND 
   c. you must notify Clare McArthur by email within 24h, summarising what has occurred (this will be reported as an adverse event to the Animal Ethics Committee even if you played no part in the injury). 
